env:
  global:
  - TERM=dumb

language: java
jdk: oraclejdk8

apt:
  update: true
  packages:
  - curl
  - bash
  - python-pip

install: true
before_script:
- sudo pip install httpie >/dev/null
- source <(curl -s https://raw.githubusercontent.com/daggerok/bash-functions/master/main.bash)
- stop_any 80 8080

script:
- bash gradlew >/dev/null
- SPRING_PROFILES_ACTIVE=dev bash ./build/libs/*.jar &
- wait_for 8080
- http :8080
- http :8080/api/
- http :8080/api/em/entity
- stop_any 80 8080 80 8080
#
- bash mvnw >/dev/null
- java  -Dspring.profiles.active=dev -jar ./target/*.jar &
- wait_for 8080
- http :8080
- http :8080/api/
- http :8080/api/em/entity
- stop_any 80 80 8080 8080

cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle
