spring:
  profiles:
    active: prod

  datasource:
    url: ${JDBC_DATABASE_URL:}
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
