spring:
  profiles:
    include:
    - spring-boot
    - data-jpa
---
spring:
  profiles:
    active: spring-boot
  output:
    ansi:
      enabled: always
server:
  port: ${PORT:8080}
app:
  base:
    url: ${APP_BASE_URL:http://127.0.0.1:8080}
---
spring:
  profiles:
    active: data-jpa

  datasource:
    username: heroku-java-buildpack-example
    password: heroku-java-buildpack-example
    hikari:
      connection-test-query: 'SELECT 1;'
  jpa:
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        temp.use_jdbc_metadata_defaults: false
---
spring:
  profiles:
    active: servlet
  h2:
    console:
      enabled: true
